server:
  port: 9001
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:lecture
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      encoding: utf-8

  jpa:
    hibernate:
      ddl-auto: create
      hbm2ddl.auto : update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug