INSERT INTO Member (name) VALUES ('test1');
INSERT INTO Member (name) VALUES ('test2');
INSERT INTO Member (name) VALUES ('test3');
INSERT INTO Member (name) VALUES ('test4');
INSERT INTO Member (name) VALUES ('test5');
INSERT INTO Member (name) VALUES ('test6');
INSERT INTO Lecture (name,max_people) VALUES ('MATH',2);
INSERT INTO Lecture (name,max_people) VALUES ('COMPUTER',3);
INSERT INTO Lecture (name,max_people) VALUES ('SCIENCE',1);
